theme: jekyll-theme-minimal
title: JazMugen1's homepage
description: Hi I am JazMugen1 and Mr-sr71 is my github username. I primarily make mugen/ikemen character edits and custom rosters. This is where I will upload my work!
